### PR TITLE
fix: typo in method name

### PR DESCRIPTION
**Pull request by nerdybynature**
Fixed typo in method name.
Changed from `GteCommitsSinceLastVersion` to `GetCommitsSinceLastVersion`

### CODE REVIEW

**Comment by nerdybynature** [comment]
Not really sure why the build is failing.
Test pass when ran locally in Visual Studio and the same workflow is successful when running in my forked repository.

**Comment by saintedlama** [comment]
Found that exception message `Unable to load shared library 'git2-106a5f2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-106a5f2: cannot open shared object file: No such file or directory` - somehow this is related to GitHub actions and libgit2sharp

**Comment by saintedlama** [comment]
I think this is related to the Ubuntu update in GitHub Actions 
image

**Comment by saintedlama** [comment]
Fixed the issue by using a preview version of LibGit2Sharp. Will merge your PR as I'm convinced it will not break the build with the fix applied in master

**Comment by saintedlama** [comment]
Build is green. Thanks for the PR 🎉

**Pull request merged**
